### ISSUE TITLE
Duration of 0ms is not shown

### ISSUE THREAD

**Issue by manuzhang** [stanleyxu2005/dashing#68]
It seems [toHumanReadableDuration](https://github.com/stanleyxu2005/dashing/blob/master/src/util/text.js#L38) will return an empty string.

**Comment by stanleyxu2005** [comment]
What is your input? Please provide some test numbers and I can reproduce and then fix the problem.

**Comment by manuzhang** [comment]
try `toHumanReadableDuration(0, true)`

**Comment by stanleyxu2005** [comment]
Oh yeah, confirmed. It actually returns an empty string. 

As the function does not take unit as input, return '0' or 'just now' could be reasonable result. Sounds good? Meanwhile you can change your code to `toHumanReadableDuration(0, true) || 'just now'`. This also works in angular template.

BTW: I don't prefer add any default unit, e.g `ms` or `us`.

**Comment by stanleyxu2005** [comment]
Fixed by showing `1<ms`, if the input is less than 1ms. (No round operation will be done internally, because it involves extra operations. See this https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary/35715420#35715420)
